name: SonarQube Analysis

on:
  push:
   
  pull_request:
   

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v5
    - name: Build with Maven and SonarQube Scan
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Qsonar.projectKey=your_project_key
        -Qsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        -Dsonar.token=${{ secrets.SONAR_TOKEN }}